config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :posts
    resources :pages
    resources :photos
    resources :albums
  end
  get '/blog/(:slug)', to: 'content#post', as: 'blog'
  get '/photos', to: 'content#photos', as: 'photos'
  get '/photos/(:slug)', to: 'content#photo', as: 'photo'
  get '/about', to: 'content#about', as: 'about'
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  class DashboardController < AdminController
    def index
      @posts = Post.all
      @pages = Page.all
      @albums = Album.all
      @photos = Photo.all
    end
  end
end

app/views/admin/dashboard/index.html.erb
<%= link_to 'Create Post', new_admin_post_path, class: 'button is-link is-outlined mb-5' %><br/>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
    <tr class="has-background-white-ter	has-text-left">
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.published %></td>
        <td><%= link_to 'Preview', admin_post_path(post), class: "button is-small is-light" %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(post), class: "button is-small is-light" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Create Page', new_admin_page_path, class: 'button is-link is-outlined mb-5' %>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
    <tr class="has-background-white-ter	has-text-left">
      <th>Title</th>
      <th>Published</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.published %></td>
        <td><%= link_to 'Preview', admin_page_path(page), class: "button is-small is-light" %></td>
        <td><%= link_to 'Edit', edit_admin_page_path(page), class: "button is-small is-light" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Create Album', new_admin_album_path, class: 'button is-link is-outlined mb-5' %>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
    <tr class="has-background-white-ter	has-text-left">
      <th>Name</th>
      <th>Slug</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.slug %></td>
        <td><%= link_to 'Edit', edit_admin_album_path(album), class: "button is-small is-light" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Add Photo', new_admin_photo_path, class: 'button is-link is-outlined mb-5' %>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
    <tr class="has-background-white-ter	has-text-left">
      <th>Title</th>
      <th>Desc</th>
      <th>Album</th>
      <th>Slug</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.name %></td>
        <td><%= photo.desc %></td>
        <td><%= photo.album.name %></td>
        <td><%= photo.slug %></td>
        <td><%= link_to 'Preview', admin_photo_path(photo), class: "button is-small is-light" %></td>
        <td><%= link_to 'Edit', edit_admin_photo_path(photo), class: "button is-small is-light" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>