config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :posts
    resources :pages
    resources :photos
    resources :albums
  end
  get '/blog/(:slug)', to: 'content#post', as: 'blog'
  get '/photos', to: 'content#photos', as: 'photos'
  get '/photos/(:slug)', to: 'content#photo', as: 'photo'
  get '/about', to: 'content#about', as: 'about'
end

app/controllers/content_controller.rb
# frozen_string_literal: true

class ContentController < ApplicationController
  def post
    @post = Post.find_by!(slug: params[:slug])
  end

  def about
    @page = Page.find_by!(slug: 'about')
  end

  def photos
    @photos = Photo.with_attached_photograph
  end

  def photo
    @photo = Photo.find_by(slug: params[:slug])
  end
end

app/views/content/about.html.erb
<section class="is-centered">
  <header class="has-text-centered">
    <h1 class="title is-1 is-size-2-mobile"><%= @page.title %></h1>
  </header>
</section>

<section>
  <div class="columns is-centered">

    <div class="column is-three-fifths is-size-5 is-size-5-mobile">
      <hr>
      <%= @page.content %>
    </div>
  </div>
</section>

app/views/content/page.html.erb
<section class="is-centered">
  <header class="has-text-centered">
    <h1 class="title is-1 is-size-2-mobile"><%= @page.title %></h1>
  </header>
</section>

<section>
  <div class="columns is-centered">

    <div class="column is-three-fifths is-size-5 is-size-5-mobile">
      <hr>
      <%= @page.content %>
    </div>
  </div>
</section>

app/views/content/photo.html.erb
<div class="columns is-centered">
  <div class="column is-three-fifths is-size-5 is-size-5-mobile">
    <div class="card has-background-white-ter">
      <div class="card-content">
        <%= image_tag @photo.photograph, width: '100%' %>
        <% if @photo.settings.present? %>
          <div class="has-text-centered is-size-7"><%= @photo.settings %></div>
        <% end %>
      </div>
    </div><br />
  </div>
</div>

app/views/content/photos.html.erb
<div class="columns is-vcentered is-centered is-multiline is-offset-one-fifth">
  <% if @photos.any? %>
  <% @photos.each do |photo| %>
  <div class="column is-one-quarter-desktop is-half-tablet ">
    <div class="card">
      <%= link_to photo_path(slug: photo.slug) do %>
      <div class="card-content">
        <%= image_tag photo.photograph, class: "image", width: '100%' %>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
    <% else %>
  Coming Soon...
    <% end %>
</div>

app/views/content/post.html.erb
<section class="is-centered">
  <header class="has-text-centered">
    <h1 class="title is-1"><%= @post.title %></h1>
    <span class="has-text-grey"><i><%= @post_date %></i></span>
  </header>
</section>

<section>
  <div class="columns is-centered">

    <div class="column is-three-fifths is-size-5 is-size-5-mobile">
      <hr>
      <%= @post.content %>
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_admin_post_path(@post), class: 'button is-link is-outlined' %>
        <%= link_to 'Back', :back, class: 'button is-outlined' %>
      <% end %>
    </div>
  </div>
</section>