config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index'
    resources :posts
    resources :pages
    resources :photos
    resources :albums
  end
  get '/blog/(:slug)', to: 'content#post', as: 'blog'
  get '/photos', to: 'content#photos', as: 'photos'
  get '/photos/(:slug)', to: 'content#photo', as: 'photo'
  get '/about', to: 'content#about', as: 'about'
end

app/views/layouts/_footer.html.erb
<footer class="footer has-background-white">
  <div class="content has-text-centered">
    <section>
      <div class="columns is-centered">

        <div class="column is-three-fifths">
          <hr>
          &#169; Copyright & Stuff like that <%= Date.today.year %>&#8226; All rights reserved.<br/>
          View on <%= link_to 'github', 'https://github.com/gharmonjr/glennjamin-blog' %> | Find me on <%= link_to 'Twitter', 'https://twitter.com/glennjamin_dev' %>

        </div>
      </div>
    </section>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar mb-6" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "#{image_tag("gj.png", width: 20) }  glennjamin.dev".html_safe, '/', class: "navbar-item has-text-weight-semibold" %>

    <a role="button" class="navbar-burger burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navMenu" class="navbar-menu">
    <div class="navbar-start has-dropdown">
    </div>
    <div class="navbar-end has-dropdown">
      <%= link_to 'about', about_path, class: 'navbar-item has-text-weight-semibold', title: 'about' %>
      <%= link_to 'photos', photos_path, class: 'navbar-item has-text-weight-semibold', title: 'about' %>
      <%#= link_to 'blog', blog_posts_path, class: 'navbar-item has-text-weight-semibold', title: 'about' %>
      <%#= link_to 'twitter', '#', class: 'navbar-item has-text-weight-semibold', title: 'about' %>
      <%#= link_to 'github', '#', class: 'navbar-item has-text-weight-semibold', title: 'about' %>
      <%# if current_user.present? && current_user.role.level == 1 %>
        <%#= link_to 'dashboard', admin_path, class: 'navbar-item has-text-weight-semibold', title: 'dashboard' %>
      <%#end %>
    </div>
  </div>
</nav>
<script type="text/javascript"> <!-- add this for menu toggle button  -->
(function() {
    var burger = document.querySelector('.navbar-burger');
    var menu = document.querySelector('#'+burger.dataset.target);
    burger.addEventListener('click', function() {
        burger.classList.toggle('is-active');
        menu.classList.toggle('is-active');
    });
})();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'favicon.ico' %>
    <%#= favicon_link_tag asset_path('glennjamin.jpg') %>


    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_pack_path('media/images/glennjamin.jpg') %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_pack_path('media/images/glennjamin.jpg') %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_pack_path('media/images/glennjamin.jpg') %>">
<!--    <link rel="mask-icon" href="<%#= asset_pack_path('media/images/safari-pinned-tab.svg') %>" color="#48b2b2">-->
    <meta name="apple-mobile-web-app-title" content="glennjamin">
    <meta name="application-name" content="glennjamin">
    <meta name="msapplication-TileColor" content="#48b2b2">
    <meta name="theme-color" content="#ffffff">

    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  </head>

  <body class="">
  <section class="section">
    <div class="container">
      <%= render 'layouts/navigation' %>

      <% flash.each do |type, msg| %>
        <div class="notification is-primary is-light">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </section>
  </body>
  <%= render 'layouts/footer' %>

</html>